import sys
import uuid
from pathlib import Path

project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from rag_citation import CiteItem, Inference


documents = [
    "Elon Musk Elon MuskCEO, Tesla$221.6B$439M (0.20%)Real Time Net Worthas of 8/6/24Reflects change since 5 pm ET of prior trading day. 1 in the world todayPhoto by Martin Schoeller for ForbesAbout Elon MuskElon Musk cofounded six companies, including electric car maker Tesla, rocket producer SpaceX and tunneling startup Boring Company.He owns about 12% of Tesla excluding options, but has pledged more than half his shares as collateral for personal loans of up to $3.5 billion.In early 2024, a Delaware judge voided Musk's 2018 deal to receive options equaling an additional 9% of Tesla. Forbes has discounted the options by 50% pending Musk's appeal.SpaceX, founded in 2002, is worth nearly $180 billion after a December 2023 tender offer of up to $750 million; SpaceX stock has quintupled its value in four years.Musk bought Twitter in 2022 for $44 billion, after later trying to back out of the deal. He owns an estimated 74% of the company, now called X.Forbes estimates that Musk's stake in X is now worth nearly 70% less than he paid for it based on investor Fidelity's valuation of the company as of December 2023.",
    "people in the world; as of August 2024[update], Forbes estimates his net worth to be US$241 billion.[3] Musk was born in Pretoria to model Maye and businessman and engineer Errol Musk, and briefly attended the University of Pretoria before immigrating to Canada at age 18, acquiring citizenship through his Canadian-born mother. Two years later, he matriculated at Queen's University at Kingston in Canada. Musk later transferred to the University of Pennsylvania and received bachelor's degrees in economics and physics.",
]

## answer generated by llm
answer = "Elon Musk's net worth is estimated to be US$241 billion as of August 2024."

## optional: custom system prompt (set to None to use the default prompt)
custom_prompt = None

## Example 1: Simple custom prompt
# custom_prompt = "You are a citation expert. For each sentence, find the exact source document that supports it."

## Example 2: Strict citation prompt - only cite when there is a direct match
# custom_prompt = """You are a strict citation assistant. For each sentence in the answer:
# 1. Only cite a sentence if the source document contains the EXACT same facts (numbers, dates, names).
# 2. If a sentence combines information from multiple sources, cite all relevant source documents.
# 3. If a sentence is not directly supported by any source, do NOT include it in the citations."""

## Example 3: Lenient citation prompt - cite even for paraphrased content
# custom_prompt = """You are a citation assistant. For each sentence in the answer:
# 1. Cite a sentence if the source document supports it, even if the wording is different.
# 2. Include partial matches where the source covers the same topic.
# 3. Prefer citing more sources rather than fewer."""


def generate_uuid():
    return str(uuid.uuid4())


context = []
for document in documents:
    context.append(
        {
            "source_id": generate_uuid(),
            "document": document,
            "meta": [
                {
                    "url": "https://www.forbes.com/profile/elon-musk/",
                    "chunk_id": "1eab8dd1ffa92906f7fc839862871ca5",
                }
            ],
        }
    )


## override the default prompt if custom_prompt is set
if custom_prompt:
    import rag_citation.llm.prompt as prompt_module
    prompt_module.CITATION_SYSTEM_PROMPT = custom_prompt


cite_item = CiteItem(answer=answer, context=context)

## set your model and api_key here
inference = Inference(
    method="llm",
    model="gpt-4o",           # or "anthropic/claude-sonnet-4-20250514", "azure/gpt-4o", etc.
    # api_key="sk-...",       # optional if set via env var (OPENAI_API_KEY, ANTHROPIC_API_KEY, etc.)
)

print("------ START --------")
output = inference(cite_item)

print("------ citation --------")
print(output.citation)

print("------ missing_word --------")
print(output.missing_word)

print("------ hallucination --------")
print(output.hallucination)
